all: mem1.c mem2.c mem_write1.c mem_write2.c mem_write3.c 
	gcc -Wall  -ggdb -o mem1 mem1.c
	gcc -Wall  -ggdb -o mem2 mem2.c
	gcc -Wall  -ggdb -o mem_write1 mem_write1.c
	gcc -Wall  -ggdb -o mem_write2 mem_write2.c
	gcc -Wall  -ggdb -o mem_write3 mem_write3.c
	
