all: if.c load.c
	gcc -Wall -ggdb -o if if.c
	gcc -Wall -ggdb -o load load.c
	gcc -Wall -ggdb -o for1 for1.c
	gcc -Wall -ggdb -o for2 for2.c
	gcc -Wall -ggdb -O3 -o for3 for2.c
	gcc -Wall -ggdb -o while1 while1.c
	gcc -Wall -ggdb -o while2 while2.c
	gcc -Wall -ggdb -o while3 while3.c
	gcc -Wall -ggdb -o while4 while4.c
	gcc -Wall -ggdb -o break1 break1.c
	gcc -Wall -ggdb -o continue continue.c
	
